# Generated by Django 2.2.13 on 2021-06-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderitem_item_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Cereals'), ('DM', 'Dairy and Milk products'), ('P', 'Pulses')], max_length=2),
        ),
    ]
